[App]
Name = "ai.h2o.wave.template.chatbot-history"
Version = "0.0.1"
Title = "Chatbot History Template"
Description = "H2O Wave Template for Chatbot Applications with History"
Tags = ["GENERATIVE_AI", "OSS"]
LongDescription = "LongDescription.md"

[Runtime]
Module = "app"
EnableOIDC = false

[[Env]]
Name = "H2OGPTE_API_TOKEN"
Secret = "h2ogpte-shared"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPTE_URL"
Secret = "h2ogpte-shared"
SecretKey = "h2ogpte-url"
