[App]
Name = "ai.h2o.link.h2ogpte"
Version = "1.1.5"
Title = "Enterprise h2oGPTe"
Description = "Information retrieval on internal data, privately hosted LLM, your data stays with you."
InstanceLifecycle = "LINK"
Tags = ["GENERATIVE_AI"]
LongDescription = "LongDescription.md"

[Link]
Address = "https://h2ogpte.genai.h2o.ai"